### ISSUE TITLE
More English.

### ISSUE THREAD

**Issue by ghost** [tomohiro-n/english-please#1]

**Comment by tomohiro-n** [comment]
Thanks for looking at it, this project was for a 1-day hackathon I held so we didn't have any time for documenting. This was kinda prototype of a support tool for visitors to find English-friendly places. Not sure if further development will be done though. Used JavaScript, Python, Elasticsearch, Yelp API etc. Fun!

**Comment by ghost** [comment]
I was only joking! Cool project BTW.
